name: SimpleFeatures
main: net.digiex.simplefeatures.SFPlugin
version: 1.0.3
description: Basic commands and features
author: jessenic
website: http://digiex.net/
database: true
commands:
    home:
        usage: |
               /<command> [world]
               Example: /<command> Survival
        aliases: [h]
        description: Teleports player to their home
    listhomes:
        usage: |
               /<command> [player]
               Example: /<command> Snookieboy
        aliases: [lh]
        description: Lists player's homes
    sethome:
        usage: |
               /<command> [world]
               Example: /<command> Survival
        aliases: [sh]
        description: Sets player's home
    spawn:
        usage: |
               /<command> [world]
               Example: /<command> Survival
        aliases: [s]
        description: Teleports player to spawn location
    setspawn:
        usage: |
               /<command> [world]
               Example: /<command> Survival
        description: Sets the spawn location
    tp:
        usage: |
               /<command> [player]
               Example: /<command> Snookieboy
        description: Teleports you to player
    tphere:
        usage: |
               /<command> [player]
               Example: /<command> Snookieboy
        description: Teleports player to you
    tpa:
        usage: |
               /<command> [player]
               Example: /<command> Snookieboy
        description: Teleports you to player with confirmation
    tpahere:
        usage: |
               /<command> [player]
               Example: /<command> Snookieboy
        description: Teleports player to you with confirmation
    world:
        usage: |
               /<command> [world]
               Example: /<command> Survival
        aliases: [w]
        description: Teleports you to another world
    who:
        aliases: [whois, whos, player, players, listplayers, list, playerlist, pl]
        description: Looks up a player, returning various details about them. If no player is specified, it lists all available players.
        usage: |
               /<command> [player]
               Example: /<command> Snookieboy
    msg:
        aliases: [priv, tell, m, pm]
        description: Sends a player a message
        usage: |
               /<command> <player> <message>
               Example: /<command> Snookieboy I smell sharks!
    reply:
        aliases: [r]
        description: Replies to the last received message
        usage: |
               /<command> <message>
               Example: /<command> Oh no!
    me:
        description: Express yourself!
        usage: |
               /<command> <message>
               Example: /<command> is a shark!
    entities:
        description: Debugging
        usage: |
               /<command> [world] [clear]
               Example: /<command> Survival
               Example: /<command> Survival clear
    abort:
        description: Aborts a teleport
        usage: |
               /<command>
               Example: /<command>
    send:
        aliases: [mail]
        description: Sends a player a offline message
        usage: |
               /<command> <player> <message>
               Example: /<command> Snookieboy I smell sharks!
    clear:
        description: Clear all mails
        usage: |
               /<command>
               Example: /<command>
    read:
        aliases: [lastmsgs]
        description: Read your mail
        usage: |
               /<command> [page]
               Example: /<command> 2
    sendall:
        aliases: [mailall]
        description: Sends all players a offline message
        usage: |
               /<command> <message>
               Example: /<command> I smell sharks!
    random:
        aliases: [rnd]
        description: Teleports you to a random location.
        usage: |
               /<command>
               Example: /<command>
    admin:
        aliases: [adm]
        description: Toggle admin mode on and off.
        usage: |
               /<command>
               Example: /<command>
    lastseen:
        aliases: [seen]
        description: Check player's last online time
        usage: |
               /<command> <player>
               Example: /<command> Snookieboy
    compasspoint:
        aliases: [cp]
        description: List/remove/add compass points
        usage: |
               /<command> <list|remove|add> [pointname]
               Example: /<command> add awesomemountain