name: SimpleFeatures
main: net.digiex.simplefeatures.SFPlugin
version: 0.0.1
description: Basic commands and features
author: jessenic
website: http://digiex.net/
database: true
commands:
    home:
        usage: |
               /<command> [world]
               Example: /<command> Survival
        aliases: [h]
        description: Teleports player to their home
    listhomes:
        usage: |
               /<command> [player]
               Example: /<command> Snookieboy
        aliases: [lh]
        description: Lists player's homes
    sethome:
        usage: |
               /<command> [world]
               Example: /<command> Survival
        aliases: [sh]
        description: Sets player's home
    spawn:
        usage: |
               /<command> [world]
               Example: /<command> Survival
        aliases: [s]
        description: Teleports player to spawn location
    setspawn:
        usage: |
               /<command> [world]
               Example: /<command> Survival
        description: Sets the spawn location
    tp:
        usage: |
               /<command> [player]
               Example: /<command> Snookieboy
        description: Teleports you to player
    tphere:
        usage: |
               /<command> [player]
               Example: /<command> Snookieboy
        description: Teleports player to you
    tpa:
        usage: |
               /<command> [player]
               Example: /<command> Snookieboy
        description: Teleports you to player with confirmation
    tpahere:
        usage: |
               /<command> [player]
               Example: /<command> Snookieboy
        description: Teleports player to you with confirmation
    world:
        usage: |
               /<command> [world]
               Example: /<command> Survival
        aliases: [w]
        description: Teleports you to another world
    who:
        aliases: [whois, whos, player, players, listplayers, list, playerlist, pl]
        description: Looks up a player, returning various details about them. If no player is specified, it lists all available players.
        usage: |
               /<command> [player]
               Example: /<command> Snookieboy
    msg:
        aliases: [priv, tell, m, pm]
        description: Sends a player a message
        usage: |
               /<command> <player> <message>
               Example: /<command> Snookieboy I smell sharks!
    reply:
        aliases: [r]
        description: Replies to the last received message
        usage: |
               /<command> <message>
               Example: /<command> Oh no!
    me:
        description: Express yourself!
        usage: |
               /<command> <message>
               Example: /<command> is a shark!
    lastmsgs:
        description: Shows last 5 messages sent to you.
        usage: |
               /<command> [from player]
               Example: /<command> Snookieboy
    entities:
        description: Debugging
        usage: |
               /<command> [world]
               Example: /<command> Survival
    abort:
        description: Aborts a teleport
        usage: |
               /<command>
               Example: /<command>